Replace placekitten images with inline images
cbracco/html5-test-page pull request #60
Opened 2024-10-17 09:18 UTC by jameswragg

placekitten.com has gone.

2025-02-27 20:13 UTC, altsalt commented
Note that https://placecats.com is a drop-in replacement.

2026-02-06 20:55 UTC, ignaziodimaio requested changes
It's better to get images from websites like [placecats.com](https://placecats.com/) instead of inline them.

2026-02-19 13:00 UTC, ignaziodimaio commented
Done in pull request #69

2026-02-20 10:16 UTC, jameswragg commented
> It's better to get images from websites like [placecats.com](https://placecats.com/) instead of inline them.

The idea of inlining them was to remove external service dependencies that eventually may disappear, as placekitten did but I'm not wedded to it. Thanks for pushing the updates - hope they get merged

2026-02-20 10:16 UTC, closed without merging